#!/usr/bin/env npx ts-node

/**
 * Import Azet.sk scraped taxi services into cities.json
 *
 * This script reads the azet-import.json file (generated by scrape-azet-taxi.ts)
 * and merges the new services into the main cities.json database.
 *
 * Usage:
 *   npx ts-node scripts/import-azet-data.ts
 *   npx ts-node scripts/import-azet-data.ts --dry-run
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface ImportService {
  name: string;
  phone: string | null;
  website: string | null;
  source: string;
  azet_url: string;
  address: string | null;
  description: string | null;
}

interface ImportData {
  citySlug: string;
  cityName: string;
  newServices: ImportService[];
}

interface ExistingTaxiService {
  name: string;
  phone: string;
  website: string | null;
  isPremium?: boolean;
  isPromotional?: boolean;
  premiumExpiresAt?: string;
}

interface City {
  name: string;
  slug: string;
  region: string;
  description: string;
  metaDescription: string;
  keywords: string[];
  taxiServices: ExistingTaxiService[];
  latitude: number;
  longitude: number;
}

interface CitiesData {
  lastUpdated: string;
  cities: City[];
}

// Normalize phone number for comparison
function normalizePhone(phone: string | null): string {
  if (!phone) return '';
  return phone.replace(/[^0-9]/g, '').slice(-9); // Last 9 digits
}

// Check if phone already exists in services
function phoneExists(phone: string | null, services: ExistingTaxiService[]): boolean {
  if (!phone) return false;
  const normalized = normalizePhone(phone);
  return services.some(s => normalizePhone(s.phone) === normalized);
}

// Interactive prompt
function askQuestion(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise(resolve => {
    rl.question(question, answer => {
      rl.close();
      resolve(answer.trim().toLowerCase());
    });
  });
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const autoApprove = args.includes('--yes') || args.includes('-y');

  // Check if import file exists
  const importPath = path.join(__dirname, '../azet-import.json');
  if (!fs.existsSync(importPath)) {
    console.log('❌ No import file found!');
    console.log('');
    console.log('Run the scraper first:');
    console.log('  npm run scrape-azet -- banska-bystrica');
    console.log('  npm run scrape-azet -- --all');
    process.exit(1);
  }

  // Load import data
  const importData: ImportData[] = JSON.parse(fs.readFileSync(importPath, 'utf-8'));

  if (importData.length === 0) {
    console.log('✅ No new services to import!');
    process.exit(0);
  }

  // Load cities data
  const citiesPath = path.join(__dirname, '../src/data/cities.json');
  const citiesData: CitiesData = JSON.parse(fs.readFileSync(citiesPath, 'utf-8'));

  // Count total new services
  const totalNew = importData.reduce((sum, d) => sum + d.newServices.length, 0);

  console.log('📋 Azet.sk Import Tool');
  console.log('='.repeat(50));
  console.log(`\n🆕 Found ${totalNew} new taxi services to import:\n`);

  // Show preview
  for (const { cityName, citySlug, newServices } of importData) {
    console.log(`📍 ${cityName} (${citySlug}):`);
    for (const service of newServices) {
      console.log(`   ➕ ${service.name}`);
      console.log(`      Phone: ${service.phone || 'N/A'}`);
      if (service.address) {
        console.log(`      Address: ${service.address}`);
      }
    }
    console.log('');
  }

  if (dryRun) {
    console.log('🔍 DRY RUN - No changes will be made');
    process.exit(0);
  }

  // Ask for confirmation
  if (!autoApprove) {
    const answer = await askQuestion('Do you want to import these services? (y/n): ');
    if (answer !== 'y' && answer !== 'yes') {
      console.log('❌ Import cancelled');
      process.exit(0);
    }
  }

  // Perform import
  let importedCount = 0;
  let skippedCount = 0;

  for (const { citySlug, newServices } of importData) {
    const city = citiesData.cities.find(c => c.slug === citySlug);

    if (!city) {
      console.log(`⚠️  City not found: ${citySlug}`);
      continue;
    }

    for (const service of newServices) {
      // Double-check phone doesn't exist (safety check)
      if (service.phone && phoneExists(service.phone, city.taxiServices)) {
        console.log(`⏭️  Skipping ${service.name} - phone already exists`);
        skippedCount++;
        continue;
      }

      // Add new service
      const newTaxiService: ExistingTaxiService = {
        name: service.name,
        phone: service.phone || '',
        website: service.website,
        isPremium: false,
        isPromotional: false
      };

      city.taxiServices.push(newTaxiService);
      importedCount++;
      console.log(`✅ Added: ${service.name} to ${city.name}`);
    }
  }

  // Update timestamp
  citiesData.lastUpdated = new Date().toISOString();

  // Save updated data
  fs.writeFileSync(citiesPath, JSON.stringify(citiesData, null, 2));

  console.log('\n' + '='.repeat(50));
  console.log('📊 IMPORT COMPLETE');
  console.log('='.repeat(50));
  console.log(`✅ Imported: ${importedCount} services`);
  console.log(`⏭️  Skipped: ${skippedCount} services`);
  console.log(`📁 Updated: ${citiesPath}`);

  // Optionally remove import file
  if (!args.includes('--keep')) {
    fs.unlinkSync(importPath);
    console.log(`🗑️  Removed: ${importPath}`);
  }

  // Reminder about meta descriptions
  if (importedCount > 0) {
    console.log('\n💡 TIP: Run the following to update meta descriptions:');
    console.log('   node scripts/improve-meta-descriptions.js');
  }
}

main().catch(console.error);
